services:
  _defaults:
    autowire: true
    public: true

  Vipinbose\HashidsBundle\Service\HashidsService:
    arguments:
      - '%vipinbose.hashids.salt%'
      - '%vipinbose.hashids.min_hash_length%'
      - '%vipinbose.hashids.alphabet%'

  Vipinbose\HashidsBundle\Interfaces\HashidsServiceInterface: '@Vipinbose\HashidsBundle\Service\HashidsService'

  Vipinbose\HashidsBundle\ValueResolver\HashIdValueResolver:
    arguments:
      $enable: '%vipinbose.hashids.enable_value_resolver%'
    tags:
      - { name: controller.argument_value_resolver, priority: 222 }

  Vipinbose\HashidsBundle\EventListener\KernelListener:
    autoconfigure: true
    arguments:
      $enable: '%vipinbose.hashids.enable_value_resolver%'
